#!/usr/bin/env python3
"""Generate a small Mermaid import map for the local Python package."""

from __future__ import annotations

import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = ROOT / "src" / "react_agent"
OUTPUT = ROOT / "docs" / "architecture" / "generated_code_map.md"


def module_name(path: Path) -> str:
    relative = path.relative_to(ROOT / "src").with_suffix("")
    parts = list(relative.parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def local_imports(path: Path) -> set[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    imports: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.update(
                alias.name for alias in node.names if alias.name.startswith("react_agent")
            )
        elif isinstance(node, ast.ImportFrom) and node.module:
            if node.module.startswith("react_agent"):
                imports.add(node.module)
    return imports


def main() -> int:
    edges: set[tuple[str, str]] = set()
    for path in sorted(PACKAGE_ROOT.rglob("*.py")):
        source = module_name(path)
        for target in local_imports(path):
            edges.add((source, target))

    lines = ["# Generated code map", "", "```mermaid", "flowchart LR"]
    if edges:
        for source, target in sorted(edges):
            lines.append(f'    "{source}" --> "{target}"')
    else:
        lines.append('    "react_agent"')
    lines.extend(["```", "", "Generated by `python scripts/generate_code_map.py`.", ""])
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
